### ISSUE TITLE
Error on first run of MCMC tutorial

### ISSUE THREAD

**Issue by JoannaDrx** [catavallejos/TutorialBASiCS#1]
##### Creating the BASiCS_Data object

Data = newBASiCS_Data(Counts = CountsQC, Tech = TechQC, SpikeInfo = SpikeInfoQC)
##### For illustration, a very short run of BASiCS

MCMC_Output <- BASiCS_MCMC(Data, N = 100, Thin = 2, Burn = 50)

_" Error in HiddenBASiCS_MCMC_Start(Data) : could not find function "newSCESet" "_

**Comment by catavallejos** [comment]
Hi Joanna,

Thanks for telling me about this. In the process of improving the starting values for the MCMC, I broke this part of the code. This is now fixed (I also updated the README file of this repository with the new dependency to 'scran'). Please reinstall BASiCS (v 0.5.10) and this should resolve the issue. 

Let me know if have any other problems. 

Best,

Catalina
